name: Laravel deploy PROD

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
  deploy:
    name: Deploy
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: SSH connection and run scripts/deploy_prod.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTPROD }}
          username: ${{ secrets.USERNAMEPROD }}
          port: ${{ secrets.PORTPROD }}
          key: ${{ secrets.SSHKEYPROD }}
          script: "cd /root/html/osmfeatures && git pull && docker exec php81_osmfeatures bash scripts/deploy_prod.sh"
