name: Run Tests

on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-3.3
        env:
          POSTGRES_PASSWORD: osmfeatures
          POSTGRES_DB: osmfeatures
          POSTGRES_USER: osmfeatures
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-scripts --no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Install osm2pgsql
        run: sudo apt-get update && sudo apt-get install -y osm2pgsql
      - name: Add hosts to /etc/hosts
        run: sudo sh -c 'echo "127.0.0.1 db" >> /etc/hosts'
      - name: Migrate
        run: php artisan migrate
        env:
          PGPASSWORD: osmfeatures
      - name: Clear the config cache
        run: php artisan config:clear
      - name: Optimize
        run: php artisan optimize
      - name: Prepare Log File
        run: mkdir -p storage/logs && touch storage/logs/test.log
      - name: Laravel Tests
        run: php artisan test --log-events-verbose-text storage/logs/test.log
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: storage/logs/test.log
